"""empty message

Revision ID: 6b6ae0510961
Revises: 9c82b345610e
Create Date: 2022-06-15 14:52:40.093516

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b6ae0510961'
down_revision = '9c82b345610e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fullname', sa.String(length=15), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'fullname')
    # ### end Alembic commands ###
